### ISSUE TITLE
[Feat- Front] 마이페이지 모달창 구현

### ISSUE THREAD

**Issue by jyhyun97** [jyhyun97/ft_transcendence#40]
### ISSUE
 * Type: `feature`
 * Detail: 마이페이지의 닉네임, 프로필 변경에 대한 모달창 구현
### TODO
- [x]  열고 닫을 수 있는 Modal 컴포넌트 만들기
- [x]  상태관리 필요한 값들(닉네임, 프로필이미지 등) utils/recoil에 정리
- [x]  닉네임, 프로필이미지를 변경할 수 있는 nickChangeModal, avatarChangeModal 구현
